Linear Regression

In [19]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
Offense2 = pd.read_csv('QB2.csv')
Offense2 = Offense2.dropna(axis='rows')
Offense2.head()

,Rk,Year,Player,Pos,AV,School,College,Height,Wt,40YD,...,Player_Code,Game Played,Pass Att,Pass Comp,Pass Yard,Pass Int,Pass TD,Rush Att,Rush Yard,Rush TD
0,59,2014,A.J. McCarron,QB,3,Alabama,College Stats,75,220,4.94,...,1022888,49,20.938776,14.000000,184.061225,0.306122,1.571429,2.428571,-1.020408,0.061224
1,148,2012,Aaron Corp,QB,0,Richmond,0,75,215,4.61,...,1035872,2,31.500000,16.000000,188.000000,1.000000,0.500000,2.000000,20.000000,0.000000
2,50,2014,Aaron Murray,QB,0,Georgia,College Stats,73,207,4.84,...,1024001,52,28.423077,17.711538,253.192308,0.788462,2.326923,5.500000,7.615385,0.307692
3,137,2008,Adam Tafralis,QB,0,San Jose State,College Stats,73,221,4.78,...,59620,36,26.722222,15.944444,197.666667,0.777778,1.388889,5.888889,14.194444,0.194444
4,119,2008,Alex Brink,QB,0,Washington State,College Stats,74,211,4.96,...,64890,35,35.914286,21.457143,274.514286,1.085714,1.971429,5.628571,4.228571,0.114286

In [28]:
XOffense = Offense2.drop(columns=["Rk","Year","Player","Pos","AV","School","College","Drafted", "Round","Draft_Outcome", "Game Played","Player_Code"])

In [29]:
X = XOffense
y = Offense2["Round"]
print(X.shape, y.shape)

(195, 16) (195,)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [31]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [32]:
classifier.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [33]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.5068493150684932
Testing Data Score: 0.32653061224489793

In [34]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [8 2 2 8 6 1 8 8 8 8]
First 10 Actual labels: [2, 8, 1, 8, 5, 8, 2, 1, 8, 4]

In [35]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

    Prediction  Actual
0            8       2
1            2       8
2            2       1
3            8       8
4            6       5
5            1       8
6            8       2
7            8       1
8            8       8
9            8       4
10           8       4
11           8       8
12           8       8
13           8       4
14           8       8
15           1       1
16           8       6
17           8       3
18           3       7
19           6       5
20           1       8
21           8       8
22           3       8
23           8       8
24           1       8
25           1       2
26           8       6
27           8       2
28           2       6
29           8       7
30           8       8
31           1       1
32           3       8
33           8       6
34           8       3
35           8       8
36           8       5
37           8       3
38           8       1
39           8       1
40           8       8
41           8       6
42           1       1
43           6       8
44           8       8
45           8       5
46           8       7
47           8       8
48           8       8